_format_version: "3.0"
services:
  - name: financial-api
    url: http://financialservices-api:8080/
    routes:
      - name: create-transaction
        paths:
          - /financial
        strip_path: true
        preserve_host: false
        methods:
          - POST
      - name: get-report
        paths:
          - /reports
        strip_path: true
        preserve_host: false
        methods:
          - GET
    plugins:
      - name: rate-limiting
        config:
          minute: 20
          policy: local

      - name: prometheus
        enabled: true
        config:
          status_code_metrics: true
          latency_metrics: true
          bandwidth_metrics: true
          upstream_health_metrics: true
          per_consumer: false
