global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "kong"
    static_configs:
      - targets: ["kong:8001"]
  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb-exporter:9216"]
  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"]
