FROM pantsel/konga:latest

USER root

# Instala netcat e o cliente do PostgreSQL
RUN apk add --no-cache netcat-openbsd postgresql-client

# Copia o script de bootstrap
COPY konga-bootstrap.sh /konga-bootstrap.sh

ENTRYPOINT ["sh", "/konga-bootstrap.sh"]